- name: Install backup gem
  command: su - {{ deploy_user }} -c "gem install backup"

- name: Run Backup generator
  command: su - {{ deploy_user }} -c "backup generate:model --trigger=db_backup"

- name: Copy new backups configs
  template: src=db_backup dest={{ deploy_dir }}/Backup/models/db_backup.rb owner={{ deploy_user }} group={{ deploy_user }}

- name: Install whenever gem
  command: su - {{ deploy_user }} -c "gem install whenever"

- name: Hourly Backup Cronjob
  cron:
    name: "hourly backup {{ postgres_db_name }}"
    minute: "0"
    job: "/bin/bash -l -c 'BACKUP_TYPE=hourly backup perform -t vital'"
    user: "{{ deploy_user }}"

- name: Daily Backup Cronjob
  cron:
    name: "daily backup {{ postgres_db_name }}"
    hour: "5"
    minute: "30"
    job: "/bin/bash -l -c 'BACKUP_TYPE=daily backup perform -t vital'"
    user: "{{ deploy_user }}"

- name: Weekly Backup Cronjob
  cron:
    name: "weekly backup {{ postgres_db_name }}"
    hour: "5"
    minute: "10"
    weekday: "0"
    job: "/bin/bash -l -c 'BACKUP_TYPE=weekly backup perform -t vital'"
    user: "{{ deploy_user }}"
