---
- name: Fetch latest Nodejs 7.x installing script
  get_url:
    url: https://deb.nodesource.com/setup_7.x
    dest: /root/nodesource

- name: Add Nodejs support
  command: bash /root/nodesource

- name: Install Nodejs
  apt: name=nodejs state=latest

- name: Install Npm
  apt: name=npm state=latest
